//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSMP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICE_DBEntities : DbContext
    {
        public ICE_DBEntities()
            : base("name=ICE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CUS> TBL_CUS { get; set; }
        public virtual DbSet<TBL_FLAV> TBL_FLAV { get; set; }
        public virtual DbSet<TBL_ITEM> TBL_ITEM { get; set; }
        public virtual DbSet<TBL_ORDER> TBL_ORDER { get; set; }
        public virtual DbSet<TBL_BILL> TBL_BILL { get; set; }
        public virtual DbSet<TBL_LOGIN> TBL_LOGIN { get; set; }
    }
}
