//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER
    {
        public int IDO { get; set; }
        public string Item { get; set; }
        public string Customer { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> PutDate { get; set; }
        public Nullable<System.DateTime> TimeDate { get; set; }
        public string Payment { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
