//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FLAV
    {
        public int FID { get; set; }
        public string FName { get; set; }
        public string FDescription { get; set; }
    }
}
