//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYSMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ITEM
    {
        public int itCod { get; set; }
        public string Name { get; set; }
        public string Decsription { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Flavor { get; set; }
        public string Size { get; set; }
    }
}
